In [1]:
import pandas as pd
import json
import numpy as np
import statsmodels
# from statsmodels import stats, inter_rater
# from stats import inter_rater

In [2]:
# for second round testing
# nanxi_cn = pd.read_csv("annotations/500_2/sample_500_batch2-Nanxi - Chinese-names.csv")
# nanxi_en = pd.read_csv("annotations/500_2/sample_500_batch2-Nanxi - English-names.csv")
# nanxi_cn = nanxi_cn.fillna(0)
# nanxi_en = nanxi_en.fillna(0)
# rukun_cn = pd.read_csv("annotations/500_2/sample_500_batch2-Rukun - Chinese-names.csv")
# rukun_en = pd.read_csv("annotations/500_2/sample_500_batch2-Rukun - English-names.csv")
# rukun_cn = rukun_cn.fillna(0)
# rukun_en = rukun_en.fillna(0)
# hang_cn = pd.read_csv("annotations/500_2/sample_500_batch2-Hang - Chinese-names.csv")
# hang_en = pd.read_csv("annotations/500_2/sample_500_batch2-Hang - English-names.csv")
# hang_cn = hang_cn.fillna(0)
# hang_en = hang_en.fillna(0)

# # for first round testing
# nanxi_cn_1 = pd.read_csv("annotations/500/sample_500_batch1-Nanxi - Chinese-names.csv")
# nanxi_en_1 = pd.read_csv("annotations/500/sample_500_batch1-Nanxi - English-names.csv")
# nanxi_cn_1 = nanxi_cn_1.fillna(0)
# nanxi_en_1 = nanxi_en_1.fillna(0)
# rukun_cn_1 = pd.read_csv("annotations/500/sample_500_batch1-Rukun - Chinese-names.csv")
# rukun_en_1 = pd.read_csv("annotations/500/sample_500_batch1-Rukun - English-names.csv")
# rukun_cn_1 = rukun_cn_1.fillna(0)
# rukun_en_1 = rukun_en_1.fillna(0)
# hang_cn_1 = pd.read_csv("annotations/500/sample_500_batch1-Hang - Chinese-names.csv")
# hang_en_1 = pd.read_csv("annotations/500/sample_500_batch1-Hang - English-names.csv")
# hang_cn_1 = hang_cn_1.fillna(0)
# hang_en_1 = hang_en_1.fillna(0)

# for MA agreement testing
# nanxi_cn = pd.read_csv("annotations/Round-1-Nanxi-MA - Chinese-names.csv")
# nanxi_en = pd.read_csv("annotations/Round-1-Nanxi-MA - English-names.csv")
# nanxi_cn = nanxi_cn.fillna(0)
# nanxi_en = nanxi_en.fillna(0)

# rukun_cn = pd.read_csv("annotations/Round-1-Rukun-MA - Chinese-names.csv")
# rukun_en = pd.read_csv("annotations/Round-1-Rukun-MA - English-names.csv")
# rukun_cn = rukun_cn.fillna(0)
# rukun_en = rukun_en.fillna(0)

# hang_cn = pd.read_csv("annotations/Round-1-Hang-MA - Chinese-names.csv")
# hang_en = pd.read_csv("annotations/Round-1-Hang-MA - English-names.csv")
# hang_cn = hang_cn.fillna(0)
# hang_en = hang_en.fillna(0)

# nanxi_cn = pd.concat([nanxi_cn, nanxi_cn_1])
# hang_cn = pd.concat([hang_cn, hang_cn_1])
# rukun_cn = pd.concat([rukun_cn, rukun_cn_1])
# nanxi_en = pd.concat([nanxi_en, nanxi_en_1])
# hang_en = pd.concat([hang_en, hang_en_1])
# rukun_en = pd.concat([rukun_en, rukun_en_1])
# assert nanxi_en.shape[0] == rukun_en.shape[0] == hang_en.shape[0]

nanxi_cn = pd.read_csv('annotations/merged_1000_rel/nanxi_cn.csv')
nanxi_en = pd.read_csv('annotations/merged_1000_rel/nanxi_en.csv')
hang_cn = pd.read_csv('annotations/merged_1000_rel/hang_cn.csv')
hang_en = pd.read_csv('annotations/merged_1000_rel/hang_en.csv')
rukun_cn = pd.read_csv('annotations/merged_1000_rel/rukun_cn.csv')
rukun_en = pd.read_csv('annotations/merged_1000_rel/rukun_en.csv')

assert nanxi_cn.shape[0] == nanxi_en.shape[0] == rukun_cn.shape[0] == rukun_en.shape[0] == hang_cn.shape[0] == hang_en.shape[0]
# nanxi_en.loc[nanxi_en['Relationship'] == 1, 'Ambiance'] = 1
# rukun_en.loc[rukun_en['Relationship'] == 1, 'Ambiance'] = 1
# hang_en.loc[hang_en['Relationship'] == 1, 'Ambiance'] = 1
# nanxi_cn.loc[nanxi_cn['Relationship'] == 1, 'Ambiance'] = 1
# rukun_cn.loc[rukun_cn['Relationship'] == 1, 'Ambiance'] = 1
# hang_cn.loc[hang_cn['Relationship'] == 1, 'Ambiance'] = 1

In [3]:
def cohen_kappa(ann1, ann2):
    """Computes Cohen kappa for pair-wise annotators.
    :param ann1: annotations provided by first annotator
    :type ann1: list
    :param ann2: annotations provided by second annotator
    :type ann2: list
    :rtype: float
    :return: Cohen kappa statistic
    """
    count = 0
    for an1, an2 in zip(ann1, ann2):
        if an1 == an2:
            count += 1
    A = count / len(ann1)  # observed agreement A (Po)

    uniq = set(ann1 + ann2)
    E = 0  # expected agreement E (Pe)
    for item in uniq:
        cnt1 = ann1.count(item)
        cnt2 = ann2.count(item)
        count = ((cnt1 / len(ann1)) * (cnt2 / len(ann2)))
        E += count

    return round((A - E) / (1 - E), 4)

In [4]:
# hang_cn.columns

In [7]:
# English name coding

categories = ['Personal_Name', 'Specialty','Positivity', 'Culture', 'Location', 'Ambiance','Pun_Creative','Romanized']
df_scores = pd.DataFrame()
average = []
for category_name in  categories:
    nanxi_list = nanxi_en[category_name].astype(int).values.tolist()
    rukun_list = rukun_en[category_name].astype(int).values.tolist()
    hang_list = hang_en[category_name].astype(int).values.tolist()

    print("===  Cohen's Kappa:", category_name, "===")

    score1 = cohen_kappa(nanxi_list, rukun_list)
    score2 = cohen_kappa(nanxi_list, hang_list)
    score3 = cohen_kappa(rukun_list, hang_list)
    df_scores[category_name] = [score1, score2, score3]
    average.append(np.mean([score1, score2, score3]))
    print("Nanxi-Rukun: ", score1)
    print("Nanxi-Hang: ", score2)
    print("Rukun-Hang: ", score3)
    print("Average: ", np.mean([score1, score2, score3]))
    print()

df_scores.loc[len(df_scores.index)] = average
df_scores = df_scores.round(4)
df_scores.to_csv('output/agreement_cohenk_en.csv', encoding='utf-8')


===  Cohen's Kappa: Personal_Name ===
Nanxi-Rukun:  0.813
Nanxi-Hang:  0.8283
Rukun-Hang:  0.7947
Average:  0.8119999999999999

===  Cohen's Kappa: Specialty ===
Nanxi-Rukun:  0.7853
Nanxi-Hang:  0.9156
Rukun-Hang:  0.7872
Average:  0.8293666666666666

===  Cohen's Kappa: Positivity ===
Nanxi-Rukun:  0.7749
Nanxi-Hang:  0.8812
Rukun-Hang:  0.7473
Average:  0.8011333333333334

===  Cohen's Kappa: Culture ===
Nanxi-Rukun:  0.8486
Nanxi-Hang:  0.8933
Rukun-Hang:  0.8215
Average:  0.8544666666666667

===  Cohen's Kappa: Location ===
Nanxi-Rukun:  0.932
Nanxi-Hang:  0.9432
Rukun-Hang:  0.9297
Average:  0.9349666666666666

===  Cohen's Kappa: Ambiance ===
Nanxi-Rukun:  0.7873
Nanxi-Hang:  0.9005
Rukun-Hang:  0.8115
Average:  0.8331

===  Cohen's Kappa: Pun_Creative ===
Nanxi-Rukun:  0.8465
Nanxi-Hang:  0.8299
Rukun-Hang:  0.8866
Average:  0.8543333333333334

===  Cohen's Kappa: Romanized ===
Nanxi-Rukun:  0.7429
Nanxi-Hang:  0.8564
Rukun-Hang:  0.7472
Average:  0.7821666666666666



In [9]:
# Chinese name coding

categories = ['Personal_Name', 'Specialty','Positivity', 'Culture', 'Location', 'Ambiance','Pun_Creative']
# categories = ['Personal_Name', 'Specialty','Positivity', 'Culture', 'Location', 'Ambiance','Pun_Creative','Origin']
df_scores_cn = pd.DataFrame()
average = []
for category_name in  categories:
    nanxi_list = nanxi_cn[category_name].astype(int).values.tolist()
    rukun_list = rukun_cn[category_name].astype(int).values.tolist()
    hang_list = hang_cn[category_name].astype(int).values.tolist()
#     df_scores_cn[category_name] = [score1, score2, score3]
    print("===  Cohen's Kappa:", category_name, "===")

    score1 = cohen_kappa(nanxi_list, rukun_list)
    score2 = cohen_kappa(nanxi_list, hang_list)
    score3 = cohen_kappa(rukun_list, hang_list)
    average.append(np.mean([score1, score2, score3]))
    print("Nanxi-Rukun: ", score1)
    print("Nanxi-Hang: ", score2)
    print("Rukun-Hang: ", score3)
    print("Average: ", np.mean([score1, score2, score3]))
    print()
    df_scores_cn[category_name] = [score1, score2, score3]

df_scores_cn.loc[len(df_scores_cn.index)] = average
df_scores_cn = df_scores_cn.round(4)
df_scores_cn.to_csv('output/agreement_cohenk_cn.csv', encoding='utf-8')
# print(df_scores_cn)

===  Cohen's Kappa: Personal_Name ===
Nanxi-Rukun:  0.8135
Nanxi-Hang:  0.8084
Rukun-Hang:  0.8486
Average:  0.8235000000000001

===  Cohen's Kappa: Specialty ===
Nanxi-Rukun:  0.9227
Nanxi-Hang:  0.9068
Rukun-Hang:  0.8807
Average:  0.9034

===  Cohen's Kappa: Positivity ===
Nanxi-Rukun:  0.7999
Nanxi-Hang:  0.8547
Rukun-Hang:  0.742
Average:  0.7988666666666667

===  Cohen's Kappa: Culture ===
Nanxi-Rukun:  0.8744
Nanxi-Hang:  0.8215
Rukun-Hang:  0.8202
Average:  0.8386999999999999

===  Cohen's Kappa: Location ===
Nanxi-Rukun:  0.8687
Nanxi-Hang:  0.9221
Rukun-Hang:  0.8661
Average:  0.8856333333333333

===  Cohen's Kappa: Ambiance ===
Nanxi-Rukun:  0.8968
Nanxi-Hang:  0.8741
Rukun-Hang:  0.8655
Average:  0.8788

===  Cohen's Kappa: Pun_Creative ===
Nanxi-Rukun:  0.9285
Nanxi-Hang:  0.8661
Rukun-Hang:  0.886
Average:  0.8935333333333334



## Fleiss Kappa

In [10]:
def get_fleiss(table, method='fleiss'):
    table = 1.0 * np.asarray(table)   #avoid integer division
    n_sub, n_cat =  table.shape
    n_total = table.sum()
    n_rater = table.sum(1)
    n_rat = n_rater.max()
    #assume fully ranked
#     assert n_total == n_sub * n_rat

    #marginal frequency  of categories
    p_cat = table.sum(0) / n_total

    table2 = table * table
    p_rat = (table2.sum(1) - n_rat) / (n_rat * (n_rat - 1.))
    p_mean = p_rat.mean()

    if method == 'fleiss':
        p_mean_exp = (p_cat*p_cat).sum()
    elif method.startswith('rand') or method.startswith('unif'):
        p_mean_exp = 1 / n_cat

    kappa = (p_mean - p_mean_exp) / (1- p_mean_exp)
    return kappa

def aggregate_raters(data, n_cat=None):
    data = np.asarray(data)
    n_rows = data.shape[0]
    if n_cat is None:
        #I could add int conversion (reverse_index) to np.unique
        cat_uni, cat_int = np.unique(data.ravel(), return_inverse=True)
        n_cat = len(cat_uni)
        data_ = cat_int.reshape(data.shape)
    else:
        cat_uni = np.arange(n_cat)  #for return only, assumed cat levels
        data_ = data

    tt = np.zeros((n_rows, n_cat), int)
    for idx, row in enumerate(data_):
        ro = np.bincount(row)
        tt[idx, :len(ro)] = ro

    return tt, cat_uni

def calculate_fleiss(lang):
        if lang == "en":
            categories = ['Personal_Name', 'Specialty','Positivity', 'Culture', 'Location', 'Ambiance','Pun_Creative','Romanized']
            # categories = ['Personal_Name', 'Specialty','Positivity', 'Culture', 'Location', 'Ambiance','Pun_Creative','Origin']
            df_scores = pd.DataFrame()
            for category_name in  categories:
                nanxi_list = nanxi_en[category_name].astype(int).values.tolist()
                rukun_list = rukun_en[category_name].astype(int).values.tolist()
                hang_list = hang_en[category_name].astype(int).values.tolist()

                print("===  Fleiss's Kappa:", category_name, "===")
                # compile list for fleiss
                raw = np.array([nanxi_list, rukun_list, hang_list]).T
#                 print(raw)
                # convert data into correct format for fleiss function
                table = aggregate_raters(raw,2)[0]
                print(table)
                fleiss = get_fleiss(table)
                df_scores[category_name] = [fleiss]
                print("Fleiss English: ", fleiss)
            df_scores = df_scores.round(4)
            df_scores.to_csv('output/fleiss_en.csv', encoding='utf-8')
        else:
            categories = ['Personal_Name', 'Specialty','Positivity', 'Culture', 'Location', 'Ambiance','Pun_Creative']
            # categories = ['Personal_Name', 'Specialty','Positivity', 'Culture', 'Location', 'Ambiance','Pun_Creative','Origin']
            df_scores = pd.DataFrame()
            for category_name in  categories:
                nanxi_list = nanxi_cn[category_name].astype(int).values.tolist()
                rukun_list = rukun_cn[category_name].astype(int).values.tolist()
                hang_list = hang_cn[category_name].astype(int).values.tolist()

                print("===  Fleiss's Kappa:", category_name, "===")
                # compile list for fleiss
                raw = np.array([nanxi_list, rukun_list, hang_list]).T
#                 print(raw)
                # convert data into correct format for fleiss function
                table = aggregate_raters(raw,2)[0]
                print(table)
                fleiss = get_fleiss(table)
                df_scores[category_name] = [fleiss]
                print("Fleiss Chinese: ", fleiss)
            df_scores = df_scores.round(4)
            df_scores.to_csv('output/fleiss_cn.csv', encoding='utf-8')

calculate_fleiss("en")
calculate_fleiss("cn") 

===  Fleiss's Kappa: Personal_Name ===
[[3 0]
 [3 0]
 [3 0]
 ...
 [3 0]
 [1 2]
 [3 0]]
Fleiss English:  0.8119258921028633
===  Fleiss's Kappa: Specialty ===
[[2 1]
 [3 0]
 [3 0]
 ...
 [3 0]
 [3 0]
 [3 0]]
Fleiss English:  0.8297380585516178
===  Fleiss's Kappa: Positivity ===
[[2 1]
 [3 0]
 [0 3]
 ...
 [0 3]
 [0 3]
 [3 0]]
Fleiss English:  0.8002442321485231
===  Fleiss's Kappa: Culture ===
[[3 0]
 [3 0]
 [3 0]
 ...
 [3 0]
 [3 0]
 [2 1]]
Fleiss English:  0.8542388052670017
===  Fleiss's Kappa: Location ===
[[3 0]
 [0 3]
 [0 3]
 ...
 [3 0]
 [3 0]
 [0 3]]
Fleiss English:  0.9349515028304276
===  Fleiss's Kappa: Ambiance ===
[[2 1]
 [3 0]
 [3 0]
 ...
 [0 3]
 [3 0]
 [3 0]]
Fleiss English:  0.833710407239819
===  Fleiss's Kappa: Pun_Creative ===
[[0 3]
 [3 0]
 [3 0]
 ...
 [3 0]
 [3 0]
 [3 0]]
Fleiss English:  0.8540611930442474
===  Fleiss's Kappa: Romanized ===
[[3 0]
 [0 3]
 [3 0]
 ...
 [3 0]
 [3 0]
 [0 3]]
Fleiss English:  0.7840830449826992
===  Fleiss's Kappa: Personal_Name ===
[[3 0]

### Finding different annotations

In [22]:
# compares two people's annotations and exports the differences
def find_diff(df1, df2, filename):
    diff = df1.compare(df2,keep_shape=True)
    diff['English_Name']=df1['English_Name']
    diff['Chinese_Name']=df1['Chinese_Name']
#     diff = diff.join(df1['English_Name'])
#     diff = diff.join(df1['Chinese_Name'])
    diff = diff.dropna(thresh = 5)
    diff.to_excel(filename)
    
find_diff(nanxi_cn,rukun_cn,'NR_cn_1.xlsx')
find_diff(hang_cn,rukun_cn,'HR_cn_1.xlsx')
find_diff(hang_cn,nanxi_cn,'HN_cn_1.xlsx')
# find_diff(nanxi_cn,rukun_cn,'NR_cn.xlsx')
# find_diff(nanxi_cn,rukun_cn,'NR_cn.xlsx')
# find_diff(nanxi_cn,rukun_cn,'NR_cn.xlsx')
# find_diff(nanxi_cn,rukun_cn,'NR_cn.xlsx')
    

ValueError: Can only compare identically-labeled (both index and columns) DataFrame objects

## Find Comments

In [19]:
def find_com(df,filename):
    df = df[df['Comments'] != 0]
    df.to_csv(filename,encoding='utf-8')
# find_com(nanxi_cn,'nanxi_cn_comments.csv')
# find_com(nanxi_en,'nanxi_en_comments.csv')
# find_com(rukun_cn,'rukun_cn_comments.csv')
# find_com(rukun_en,'rukun_en_comments.csv')
find_com(hang_en,'hang_en_comments.csv')
find_com(hang_cn,'hang_cn_comments.csv')